### ISSUE TITLE
若对方ip地址为192.168.45.130

### ISSUE THREAD

**Issue by yzj0911** [hequan2017/go-webssh#1]
启动服务

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ws/:id                   --> webssh/core.WsSsh (4 handlers)
[GIN-debug] Environment variable PORT is undefined. Using port :8080 by default
[GIN-debug] Listening and serving HTTP on :8080

是否输入地址 localhost:8080/ws/192.168.45.130

**Comment by hequan2017** [comment]
我这个例子 ，后面不用带ip。 

实际情况需要把请求的ip地址 传过去。

具体你可以看下代码。

**Comment by yzj0911** [comment]
func main() {
	r := gin.Default()
	r.Use(Cors())
	r.GET("/ws/:id", core.WsSsh)
	_ = r.Run() // listen and serve on 0.0.0.0:8080
}
那我直接访问192.168.45.130就可以了？不成功呀

**Comment by hequan2017** [comment]
- -，你可以多看看代码逻辑。需要把ip写到代码里面。后面可以你可以自己改。

**Comment by yzj0911** [comment]
其实是
Bad Request
{"msg":"websocket: not a websocket handshake: 'Upgrade' token not found in 'Connection' header","ok":false}
这个不知道咋回事

**Comment by hequan2017** [comment]
我记得 我没加需要token验证呀。

**Comment by yzj0911** [comment]
func (u *Upgrader) Upgrade(w http.ResponseWriter, r *http.Request, responseHeader http.Header) (*Conn, error) {
	if r.Method != "GET" {
		return u.returnError(w, r, http.StatusMethodNotAllowed, "websocket: not a websocket handshake: request method is not GET")
	}

	if _, ok := responseHeader["Sec-Websocket-Extensions"]; ok {
		return u.returnError(w, r, http.StatusInternalServerError, "websocket: application specific 'Sec-Websocket-Extensions' headers are unsupported")
	}

	if !tokenListContainsValue(r.Header, "Connection", "Upgrade") {
		return u.returnError(w, r, http.StatusBadRequest, "websocket: not a websocket handshake: 'Upgrade' token not found in 'Connection' header")
	}

	if !tokenListContainsValue(r.Header, "Upgrade", "websocket") {
		return u.returnError(w, r, http.StatusBadRequest, "websocket: not a websocket handshake: 'websocket' token not found in 'Upgrade' header")
	}

	if !tokenListContainsValue(r.Header, "Sec-Websocket-Version", "13") {
		return u.returnError(w, r, http.StatusBadRequest, "websocket: unsupported version: 13 not found in 'Sec-Websocket-Version' header")
	}
websocket这不是调用了他的方法吗？

**Comment by hequan2017** [comment]
我当时测试是没啥问题，回头我有时间，把例子完善一下。

**Comment by yzj0911** [comment]
你当初是在core/ssh.go 修改了ip地址和对应的linux的root密码对吗？其他没做改动？

**Comment by yzj0911** [comment]
然后在自己的浏览器页面输入自己的端口：8080是这样吗

**Comment by hequan2017** [comment]
其他地方 可能有稍微的改动，具体可以看下 原来的那个项目里面的代码。

**Comment by hequan2017** [comment]
然后在自己的浏览器页面输入自己的端口：8080是这样吗

是

**Comment by yzj0911** [comment]
我登录照着你的操作是404错误

**Comment by hequan2017** [comment]
- -, 404是路由找不到。看下后端请求

**Comment by yzj0911** [comment]
Request URL: http://localhost:8080/
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:8080
Referrer Policy: no-referrer-when-downgrade
Content-Length: 18
Content-Type: text/plain
Date: Wed, 30 Oct 2019 07:30:38 GMT

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Connection: keep-alive
Cookie: Idea-951b2ee1=a394e33d-11e2-447f-b06b-c1754d020ed5; Goland-c3f280b7=b74d722d-edc1-4545-9e11-5aee50c81b1c
Host: localhost:8080
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36

**Comment by yzj0911** [comment]
好像是origin := c.Request.Header.Get("Origin") //请求头部，这里返回了空值，这个方法是做什么的？

**Comment by yzj0911** [comment]
你好，我想知道你运行成功后的页面是什么样子的，可以吗？

**Comment by hequan2017** [comment]
本项目代码来自 https://github.com/dejavuzhou/felix
